version: '3.3'
services:
  mongodb:
    image: mongo:5.0.5
    volumes:
      - mongodata:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: user1
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_password
    secrets:
      - mongodb_password
    ports:
      - ${TON_TELEMETRY_MONGODB_PORT:-27017}:27017
    networks: 
      - internal
  main:
    build: 
      context: .
      dockerfile: infrastructure/main.Dockerfile
    secrets:
      - mongodb_password
      - api_keys
      - hash_salt
      - geoip_country_db
      - geoip_isp_db
    ports:
      - ${TON_TELEMETRY_HTTP_PORT:-80}:8081
    depends_on: 
      - mongodb
    restart: unless-stopped
    networks:
      - internal
    command: -w ${TON_TELEMETRY_WEBSERVERS_WORKERS:-1} --bind 0.0.0.0:8081
secrets:
  mongodb_password:
    file: private/mongodb_password
  api_keys:
    file: private/api_keys
  hash_salt:
    file: private/hash_salt
  geoip_country_db:
    file: private/GeoIP2-Country.mmdb
  geoip_isp_db:
    file: private/GeoIP2-ISP.mmdb
volumes:
  mongodata:
    external: false
  nginxdata:
    external: false
networks:
  internal:
